---
all:
  children:
    test:
      hosts:
        TestEC2:
      vars:
        ansible_host: ec2-3-91-12-34.compute-1.amazonaws.com
        ansible_connection: ssh
        app_env: test
        compose_project_dir: /opt/docker_data/wordpress_test
        deploy_dir_uploads: /opt/docker_data/wordpress_test/uploads
        deploy_dir_conf: /opt/docker_data/wordpress_test/conf
        backup_path_test: /opt/docker_data/wordpress_test/backups/mysql/dumps
        docker_image_name_mysql: 'mysql:8.0.44'
        docker_container_name_wp: 'wordpress-test'
        docker_container_name_nginx: 'nginx-test'
        docker_container_name_mysql: 'mysql-test'
        docker_ports_nginx: '127.0.0.1:8080:80'
        docker_ports_mysql: '127.0.0.1:3307:3306'
        docker_volume_name: 'www'   
  vars:
    ansible_user: ec2-user
    ansible_port: 22
    become: yes
    ansible_ssh_private_key_file: /home/ec2-user/.ssh/id_rsa